version: "3.5"

services:
  tpe-crud:
    image: wfelipe2011/tpe-crud-prod:master
    restart: unless-stopped
    ports:
      - "4578:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    environment:
      - DATABASE_URL=$DATABASE_URL
      - JWT_SECRET=$JWT_SECRET
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY


