version: "3.5"

services:
  tpe-crud:
    image: wfelipe2011/tpe-crud-prod:master
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    networks:
      - npm_public

networks:
  npm_public:
    external: true
